### ISSUE TITLE
"TechExpo Stat 1" job always timeout

### ISSUE THREAD

**Issue by thuhoang7285** [scattm/DanceCat#88]
Should cache to avoid run from the beginning while the data is growing and obese with time

**Comment by scattm** [comment]
Thank 🎋 

Look like the driver is not using job's timeout option so I need to investigate further. Will fix this in this release. Meanwhile please try to re-run the job after it failed, you may have it done.

Please do not add job's name in future issue. My collaboration does not know about it.

**Comment by scattm** [comment]
Actually this was cause by RQ timeout.

**Comment by scattm** [comment]
Done in #96
