### ISSUE TITLE
Auto scheduled job cannot reach recipient on time or even cannot send to recipient

### ISSUE THREAD

**Issue by thuhoang7285** [scattm/DanceCat#90]
This issue may be caused by email server configuration:
1- Cannot reach recipient email at the time configured for that scheduled job (really late arrival)
2- Cannot send to recipient email

**Comment by scattm** [comment]
There are two reason result can't reach the recipient email:
- Too big result (Will be resolved in #92)
- Email server do not work (more likely in your case)

You may need your email server repaired, or use mail agent to solve the second case.

Regards.
