### ISSUE TITLE
DEV - AESDecrypt return wrong password for 14 length string

### ISSUE THREAD

**Issue by scattm** [scattm/DanceCat#93]
Function: aes_decrypt
Location: https://github.com/scattm/DanceCat/blob/dev/DanceCat/Helpers.py#L166
For example:
- Input data to `aes_encrypt`: 8ajYk2aaaaaaab
- Expected output from `aes_decrypt`: 8ajYk2aaaaaaab
- Actually output: 8ajYk2aaaaaaa

Need to investigate and fix.

**Comment by caohhung** [comment]
Please point this issue to function that causes it. E.g: https://github.com/scattm/DanceCat/blob/dev/DanceCat/Helpers.py#L140

**Comment by scattm** [comment]
This was cause by `aes_raw_pad` function that return wrong padded string.

https://github.com/scattm/DanceCat/blob/dev/DanceCat/Helpers.py#L105

**Comment by scattm** [comment]
Done #94
